chore: bump dependencies

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -1,19 +1,20 @@
-name: Deploy application
+name: Deploy app
 permissions: write-all
 
 on:
-  workflow_dispatch:
   push:
     tags:
-      - v*
+      - v[0-9]+.[0-9]+.[0-9]+
+  workflow_dispatch:
+
+concurrency:
+  group: ${{ github.workflow }}
+  cancel-in-progress: true
 
 jobs:
   deploy-app:
-    name: Deploy application
+    name: Deploy app
     runs-on: ubuntu-latest
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref_name }}
-      cancel-in-progress: true
 
     steps:
       - name: Check if the type is 'tag'
@@ -27,18 +28,31 @@ jobs:
         id: get-version-from-tag
         uses: frabert/replace-string-action@v2
         with:
-          pattern: v(.*)
-          replace-with: $1
+          pattern: ^v(\d+)\.(\d+)\.(\d+)$
+          replace-with: $1.$2.$3
           string: ${{ github.ref_name }}
 
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Extract version from package
+        id: extract-version-from-package
+        uses: sergeysova/jq-action@v2
+        with:
+          cmd: jq .version package.json -r
+
+      - name: Verify versions match
+        if: ${{ steps.get-version-from-tag.outputs.replaced != steps.extract-version-from-package.outputs.value }}
+        run: |
+          echo "::error::Version in the package.json and tag don't match"
+          exit 1
+        shell: bash
+
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           cache: npm
-          node-version: 20
+          node-version: 22.14
 
       - name: Install dependencies
         run: npm ci --ignore-scripts
@@ -69,25 +83,9 @@ jobs:
       - name: Upload build artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          name: github-pages
           path: out
-          retention-days: 1
-
-      - name: Create release
-        id: create-release
-        if: ${{ github.event_name != 'workflow_dispatch' }}
-        uses: ncipollo/release-action@v1
-        with:
-          name: Version ${{ steps.get-version-from-tag.outputs.replaced }}
-          tag: ${{ github.ref_name }}
-          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
-
-      - name: Delete release and tag on error
-        if: ${{ (failure() || cancelled()) && steps.create-release.conclusion == 'success' }}
-        run: gh release delete ${{ github.ref_name }} --cleanup-tag
-        shell: bash
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
